version: '3.2'
services:
    postgresql:
        container_name: "postgresql"
        image: postgres:12
        ports: 
            - "5432:5432"
        volumes:
            - psql_drive:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=dev
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=admin

    rabbitmq:
        container_name: "rabbitmq"
        image: "rabbitmq:3-management"
        ports:
            - "15672:15672"
            - "5672:5672"
        environment:
            RABBITMQ_DEFAULT_USER: "rabbitmq"
            RABBITMQ_DEFAULT_PASS: "rabbitmq"
            RABBITMQ_DEFAULT_VHOST: "DEV"
        restart: always

    amqpbridge:
        container_name: "amqpbridge"
        image: amqpbridge
        restart: always

volumes:
    psql_drive:
